apiVersion: v1
kind: Service
metadata:
  name: monitor-scale
  labels:
    app: monitor-scale
spec:
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  selector:
    app: monitor-scale
    tier: monitor-scale
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-scale
  labels:
    app: monitor-scale
    tier: monitor-scale
spec:
  selector:
    matchLabels:
      app: monitor-scale
      tier: monitor-scale
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: monitor-scale
        tier: monitor-scale
    spec:
      serviceAccountName: monitor-scale
      containers:
      - image: 127.0.0.1:30400/monitor-scale:$BUILD_TAG
        name: monitor-scale
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
          name: monitor-scale
      - image: zappi/kubectl:latest
        name: kubectl-api
        args: ["proxy","-p","2345"]
        ports:
        - containerPort: 2345
          name: kubectl-api          

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitor-scale
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: monitor-scale.10.148.0.6.xip.io 
    http:
      paths:
      - path: /.*
        pathType: prefix
        backend:
          service:
            name: monitor-scale
            port:
              number: 3001
